language: python
sudo: false
python:
  - "2.7"
  - "3.6"

install:
  - pip install pipenv

script:
  - pipenv install --dev --skip-lock
  - make unit functional

after_success:
  - bash <(curl -s https://codecov.io/bash)
